spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/dukq0418/nz1905.git
          search-paths: respo

server:
  port: 6666

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
